### PR TITLE
Notmp

### LINKED ISSUE #313: Document embedded rules
i.e. [this bad boy](https://github.com/dapphub/klab/blob/master/resources/rules.k.tmp).

### PR DESCRIPTION
**Pull request by asymmetric**
Renames `rules.k.tmp` to `rules.k` and documents it in the README.

Closes #313.

### CODE REVIEW

**Comment by asymmetric** [comment]
This would break all existing spec repos, if they were to be run again, cause they always [fetch the latest klab](
https://github.com/dapp-org/buildbot-nixops/tree/d44d677634e7222fc3b8e2ef78ee378f81e64cc0/master.cfg#L103).

**Comment by asymmetric** [comment]
@mhhf thanks for chiming in. Could we instead add the [required boilerplate](https://github.com/dapphub/klab/blob/notmp/lib/build.js#L147-L156) to `rules.k`?

**Comment by mhhf** [comment]
@asymmetric Yes, thats possible, but this would still keep it a template not make it valid `.k` as you need to insert rules from various places (e.g. storage.k.md, lemmas.k.md, dirty_lemmas.k.md) inside the module block from your link. Also it would create the need of coming up with a templating system for parsing and inserting the necessary information.

**Comment by asymmetric** [comment]
> What problem are you trying to solve by renaming it?

I think having this mysterious file ending in `.tmp` wasn't really good for comprehending what's going on, but that's partly taken care of by documenting it.

I guess yes, we could rename it to `.tmp` or something and that would be a step in the good direction.

**Pull request merged**
