### PR TITLE
build.js: failure act (only produces fail case)

### PR DESCRIPTION
**Pull request by gbalabasquer**

### CODE REVIEW

**Comment by MrChico** [comment]
Can we get an example demonstrating how this works? And then we can add that in the Makefile to the ci and get it tested!

**Comment by gbalabasquer** [comment]
@MrChico sure, I'll do something and update the PR.

**Comment by livnev** [comment]
It would be nice to have a test case for `failure`, added to one of the `examples/`. The CI passed, so at least it didn't break the existing `behaviour` syntax.

**Comment by livnev** [comment]
It doesn't necessarily need to be a new example, can be an extra overlapping case for one of the existing ones.

**Comment by gbalabasquer** [comment]
@livnev we could easily prove it adding `require(to != msg.sender);` to the `transfer` function of the token example. That would replicate the same behavior we have in the manager `give` function.
If you like the idea, I can do the change.

**Comment by livnev** [comment]
> @livnev we could easily prove it adding `require(to != msg.sender);` to the `transfer` function of the token example. That would replicate the same behavior we have in the manager `give` function.
> If you like the idea, I can do the change.

Yeah, that is fine with me. 😄

**Comment by gbalabasquer** [comment]
@livnev @MrChico example added and the CI passed.
Checking manually the log it only builds the `fail_rough` spec for `Token_transfer-same` which is the correct behavior.

**Pull request merged**
