### PR TITLE
Martinbranch

### PR DESCRIPTION
**Pull request by MrChico**
Contains a crucial fix for callsupport, support for internal calls using soildity's AST representation and a crucial fix in config.js making sure the source code of contracts is handled properly

### CODE REVIEW

**Comment by mhhf** [comment]
isn't AST part of the solc json output? why the separate file?

**Comment by MrChico** [comment]
No, the ast can't be included in the sol.json for sole reason. It's generated with `solc - - ast-json`

**Comment by mhhf** [comment]
hmm, seems similar to me:
```
diff \
 <(curl -s https://raw.githubusercontent.com/dapphub/klab/897a98e6649923d7b6f92d83f5222efb63016370/examples/multipleCalls/dapp/out/easyNest.sol_json.ast | jq ".") \
 <(curl -s https://raw.githubusercontent.com/dapphub/klab/897a98e6649923d7b6f92d83f5222efb63016370/examples/multipleCalls/dapp/out/easyNest.sol.json |jq '.sources["src/easyNest.sol"].AST')
```

**Comment by MrChico** [comment]
I stand corrected

**Pull request closed without merging**
