### PR TITLE
Evmbump

### PR DESCRIPTION
**Pull request by MrChico**

### CODE REVIEW

**Comment by asymmetric** [comment]
Did this not get merged because of issues?

**Comment by MrChico** [comment]
I felt like I had to do a lot of ad hoc changes to support the latest evms and I wasn't ready to break other specs at the time

**Comment by xwvvvvwx** [comment]
In what way would specs be broken by this `evms` version bump?

**Comment by asymmetric** [comment]
Closed in favor of #297.

**Pull request closed without merging**
