### PR TITLE
rules.k.tmp More compact hashing format

### PR DESCRIPTION
**Pull request by MrChico**

### CODE REVIEW

**Comment by mhhf** [comment]
can you try this with dirty lemmas first? this would rerun everything again

**Comment by MrChico** [comment]
I need to change the semantics of `     rule keccak(WS) => keccakIntList(bytesToWords(WS))` so I don't think so

**Comment by MrChico** [comment]
Actually, there is a way, let me try it

**Comment by rainbreak** [comment]
@MrChico this breaks the build

**Comment by rainbreak** [comment]
@MrChico build succeeds now. Let's hold off merge until we're ready for a ci rebuild.

**Pull request merged**
