### PR TITLE
kast: add constants & infix operators

### PR DESCRIPTION
**Pull request by xwvvvvwx**
constants:

- maxUInt32
- pow112
- maxUInt112
- pow224

infix:

- bitwise AND
- bitwise OR

### CODE REVIEW

**Comment by desaperados** [comment]
Nice, this will allow us to keep the uniswap lemmas file nice and clean 👍

**Comment by xwvvvvwx** [comment]
This doesn't affect our lemmas afaik, it only makes the output in `klab debug` easier to read.

**Comment by desaperados** [comment]
Hah, of course, it's probably my head that needs the clean

**Comment by xwvvvvwx** [comment]
CI passed, not sure why the status isn't showing up in here in github: https://buildbot.dapp.ci/#/builders/2/builds/466.

**Pull request merged**
