### PR TITLE
Lev testing performance

### PR DESCRIPTION
**Pull request by livnev**
Testing why our tests took a performance hit. 

try removing `#And` and `#unsigned` from `--output-tokenize` in `klab prove` so we can be sure that `run.sh` and `klab prove` are exactly the same...

### CODE REVIEW

**Comment by livnev** [comment]
Tried removing `--output-tokenize` completely, let's see what happens...

**Comment by mhhf** [comment]
Seems like we can't merge it due to docker

**Comment by mhhf** [comment]
when merge

**Comment by livnev** [comment]
> Seems like we can't merge it due to docker

No, we can't merge it because it needs a review. Please review and merge. :+1:

**Comment by mhhf** [comment]
closing in favor of #138

**Pull request closed without merging**
