### PR TITLE
add support for creates storage

### PR DESCRIPTION
**Pull request by desaperados**
prefacing storage blocks with `creates` will set the expectation
that the contract is to be created at runtime e.g.

```act
for all

    A : address
    B : uint256

creates storage A

    0 -> B
```

### CODE REVIEW

**Comment by livnev** [comment]
Excited for this!

**Comment by MrChico** [comment]
Sweet! Maybe we should add an example of (and run it as a ci test)

**Comment by desaperados** [comment]
It's not quite there yet - I need to stop this from happening: https://gist.github.com/desaperados/b1c2426738a72f5767d7c5ccd05bf931

**Comment by desaperados** [comment]
I notice that K throws the [same error](https://gist.github.com/desaperados/b1c2426738a72f5767d7c5ccd05bf931) on master when it encounters `new Contract`.

**Comment by desaperados** [comment]
Nice to see this working!

**Comment by desaperados** [comment]
Rebased on latest master, the example spec is passing. Looks good to merge.

**Comment by MrChico** [comment]
@desaperados hmm, I don't see the example spec being run in ci though. Added it to the examples in the makefile and we'll see

**Comment by desaperados** [comment]
Oh interesting - it passed on my machine but failed on the CI.

**Comment by desaperados** [comment]
I see I spoke too soon - I only checked the pass spec locally.

**Pull request merged**
