### PR TITLE
build: let storage be prefixed by the contract type, not name

### PR DESCRIPTION
**Pull request by MrChico**

### CODE REVIEW

**Comment by asymmetric** [comment]
Will specs have to be rewritten?

**Comment by MrChico** [comment]
Only when contract typenames and variables have different names, I haven't seen any such examples in the wild

**Comment by kmbarry1** [comment]
Actually, this will potentially cause issues with locally defined contract aliases, e.g. when one has an act like:

```
behaviour drip of Jug
interface drip(bytes32 ilk)

for all

    Vat    : address VatLike
.
.
.

storage Vat
```

The storage prefix will be #VatLike, but needs to be #Vat. I'm getting around this in my proofs currently by writing `Vat : address Vat` instead.

**Comment by kmbarry1** [comment]
To be clear, that example is taken from an actual k-dss act: https://github.com/dapphub/k-dss/blob/master/src/dss.md#updating-the-rates

**Comment by MrChico** [comment]
Latest changes are here https://github.com/dapphub/k-dss/blob/formal-professional-services/src/dss.md#updating-the-rates

**Pull request merged**
